// <auto-generated />
using EstateMgrCore.DataAccess;
using EstateMgrCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace EstateMgrCore.Migrations
{
    [DbContext(typeof(AgencyDbContext))]
    [Migration("20180312135119_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("EstateMgrCore.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adrress");

                    b.Property<string>("City");

                    b.Property<float>("Latitude");

                    b.Property<float>("Longitude");

                    b.Property<int>("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("EstateMgrCore.Models.Estate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AddressId");

                    b.Property<int>("FloorNumber");

                    b.Property<int>("FloorsCount");

                    b.Property<int>("OwnerId");

                    b.Property<int>("PropertyTax");

                    b.Property<int>("ReferentId");

                    b.Property<int>("RoomsCount");

                    b.Property<float>("Surface");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ReferentId");

                    b.ToTable("Estates");
                });

            modelBuilder.Entity("EstateMgrCore.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AddressId");

                    b.Property<string>("CellPhone");

                    b.Property<string>("FirstName");

                    b.Property<string>("Mail");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("EstateMgrCore.Models.Estate", b =>
                {
                    b.HasOne("EstateMgrCore.Models.Address", "AddressEstate")
                        .WithMany("Estates")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EstateMgrCore.Models.Person", "Referent")
                        .WithMany("Estates")
                        .HasForeignKey("ReferentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EstateMgrCore.Models.Person", b =>
                {
                    b.HasOne("EstateMgrCore.Models.Address", "AddressPerson")
                        .WithMany("Persons")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
